      common/camcom_i/Cursor$Number,font,xwin,ywin
      integer Cursor$Number,font,xwin,ywin
      common/camcom_r/size,rotation,italic,scale_X,scale_Y
      real size,italic,rotation,scale_X,scale_Y
      common/camcom_c/Status$Text
      character*80 Status$Text
      common/cam_handles/DialogHandle,GraphicsHandle
      integer DialogHandle,GraphicsHandle
      common/mouse_info/ikeym
      integer ikeym(4)

