!
! >>>>>> Function declararations 'ciftbx.cmf'
!        These external declarations are needed complete
!        the user definitions in ciftbx.cmn
         logical   init_
         logical   dict_
         logical   ocif_
         logical   data_
         logical   test_
         logical   bkmrk_
         logical   find_
         logical   name_
         logical   numb_
         logical   numd_
         logical   char_
         logical   cmnt_
         logical   pfile_
         logical   pdata_
         logical   pchar_
         logical   pcmnt_
         logical   pnumb_
         logical   pnumd_
         logical   ptext_
         logical   ploop_
         logical   prefx_
         external   init_
         external   dict_
         external   ocif_
         external   data_
         external   test_
         external   bkmrk_
         external   find_
         external   name_
         external   numb_
         external   numd_
         external   char_
         external   cmnt_
         external   pfile_
         external   pdata_
         external   pchar_
         external   pcmnt_
         external   pnumb_
         external   pnumd_
         external   ptext_
         external   ploop_
         external   prefx_



