C $Log: not supported by cvs2svn $
C Revision 1.5  2001/10/05 13:31:50  ckp2
C
C Implementation of Lists 40 and 41.
C ===================================
C New commands:
C #LIST 41 - contains a list of bonds and bondtypes. It is generated by typing
C #BONDCALC which calculates bonds from LIST1,2,5,29 and 40.
C 40 contains info about how to do the bond calculation and can override
C covalent radii, force or break specific bonds and set limits for pairs
C of elements.
C #PUNCH 40 A - produces a LIST 40, #PUNCH 40 B - produces a #BONDING command
C which may be used to input a list 40 in a more user friendy manner (no READ
C card). #BONDING may also be used to EXTEND an existing list 40.
C #SUM L 40 - summary of bonding building info. #SUM L 41 - the bonds.
C #BONDCALC creates a L40 if there is none, and also only carries out calculation
C if significant change has occured to L5. (unless "#BONDCALC FORCE").
C See manual for more details.
C
C Revision 1.4  2001/02/26 10:25:31  richard
C Added changelog to top of file
C
C
CODE FOR DISTAN
      SUBROUTINE DISTAN
      CALL XSYSDC(-1,1)
      CALL XDISTC
      RETURN
      END
C
CODE FOR XDISTC
      SUBROUTINE XDISTC
C--MAIN DISTANCE ANGLES CONTROL ROUTINE.
\XUNITS

C--LOAD THE NEXT '#INSTRUCTION'

      NUM=KNXTOP(LSTOP,LSTNO,ICLASS)
C--CHECK IF WE SHOULD RETURN
      IF(NUM.LE.0) RETURN
C--BRANCH ON THE TYPE OF OPERATION

      GOTO (2100, 2200, 8100, 8000, 2200, 2300, 2400,
     1      2500, 2600, 2700, 2800, 1300),NUM
1300   CALL GUEXIT(53)

C--DISTANCE ANGLES CALCULATION
2100  CONTINUE
      CALL XDIST
      RETURN
C
C--- #PEAKS OR \REGROUP
2200  CONTINUE
      CALL XCOND
      RETURN

C--'#COLLECT'
2300  CONTINUE
      CALL XCOLL
      RETURN

C----- #LABEL
2400  CONTINUE
C ----- LABEL REMOVED FEB 97
      RETURN

C----- #OCCMOD
2500  CONTINUE
C----- OCCMOD REMOVED FEB 97
      RETURN

C----- #AUTOMATIC
2600  CONTINUE
c      CALL AUTOMA
C----- AUTOMA REMOVED FEB 97
      RETURN

C--- #BONDING
2700  CONTINUE
      CALL XBOND
      RETURN

C--- #BONDCALC
2800  CONTINUE
      CALL XBCALC
      RETURN

C--'#END' INSTRUCTION
8000  CONTINUE
      CALL XMONTR(-1)
      CALL XEND
      RETURN

C--'#TITLE' INSTRUCTION
8100  CONTINUE
      CALL XRCN
      RETURN
      END

