CODE FOR FIDDLE
      SUBROUTINE FIDDLE
      CALL XSYSDC(-1,1)
      CALL XDISCA
      RETURN
      END
C
CODE FOR XDISCA
      SUBROUTINE XDISCA
C--CONTROL ROUTINE FOR DISC MODIFICATION ROUTINES
C
\XUNITS
\XERVAL
&PPC\XGSTOP
C
C
C--
C
C -- READ THE NEXT INSTRUCTION CARD, AND CHECK IF IT IS FOR THIS SECTION
1000  CONTINUE
      NUM=KNXTOP(I,J,K)
      IF(NUM)1100,1100,1200
C--NOT FOR US  -  RETURN
1100  CONTINUE
      RETURN
C--BRANCH ON THE TYPE OF OPERATION
1200  CONTINUE
C
       GO TO ( 2100 , 2200 , 2300 , 2400 , 1300 , 2600 , 1300 ) , NUM
1300  CONTINUE
      CALL XERHND ( IERPRG )
      STOP 600
C
C
C--'#END' CARD  -  END OF THE JOB
2100  CONTINUE
      CALL XMONTR(-1)
      CALL XEND
&PPCCS***
&PPC          GOTO 1100
&PPCCE***
C
C--'#TITLE' CARD  -  READ A NEW TITLE
2200  CONTINUE
      CALL XRCN
      GOTO 1000
C
C--'#DISC' INSTRUCTION  -  DISC MODIFICATION INSTRUCTIONS
2300  CONTINUE
      CALL XDISCF
      GOTO 1000
C
C--'#PURGE' INSTRUCTION
2400  CONTINUE
      CALL XPURGE
      GOTO 1000
C
C
2600  CONTINUE
      CALL XSIMUL
      GO TO 1000
C
      END
C
