C $Log: not supported by cvs2svn $
C Revision 1.3  2001/02/26 10:26:47  richard
C Added changelog to top of file
C
C
CODE FOR FOURIE
      SUBROUTINE FOURIE
      CALL XSYSDC(-1,1)
      CALL XFOURA
      RETURN
      END
C
CODE FOR XFOURA
      SUBROUTINE XFOURA
C--MAIN CONTROL ROUTINE FOR FOURIER CALCULATIONS

\ISTORE
\ICOM24
\STORE
\XUNITS
\XLST12
\XLST24
\XLST50
\QSTORE
\QLST24

C--LOAD THE NEXT '#INSTRUCTION'
      NUM=KNXTOP(LSTOP,LSTNO,ICLASS)

C--CHECK IF WE SHOULD RETURN
      IF(NUM.LE.0) RETURN
C--BRANCH ON THE TYPE OF OPERATION

      GOTO (2000,8000,8100,1300),NUM

1300  CALL GUEXIT(541)

C--'#FOURIER' INSTRUCTION
2000  CONTINUE
      CALL XFOURB
      RETURN

C--'#END' INSTRUCTION
8000  CONTINUE
      CALL XMONTR(-1)
      CALL XEND
      RETURN

C--'#TITLE' INSTRUCTION
8100  CONTINUE
      CALL XRCN
      RETURN
      END

