C $Log: not supported by cvs2svn $
C Revision 1.3  2001/02/26 10:26:48  richard
C Added changelog to top of file
C
C
CODE FOR GEOMET
      SUBROUTINE GEOMET
      CALL XSYSDC(-1,1)
      CALL XGEOM
      RETURN
      END
C
CODE FOR XGEOM
      SUBROUTINE XGEOM
C--CONTROL ROUTINE FOR GEOMETRICAL CALCULATIONS
\XUNITS

C--LOAD THE NEXT '#INSTRUCTION'
      NUM=KNXTOP(LSTOP,LSTNO,ICLASS)

C--CHECK IF WE SHOULD RETURN
      IF(NUM.LE.0) RETURN

C--BRANCH ON THE TYPE OF OPERATION
1200  CONTINUE
      GOTO (2000,3000,4000,5000,1300),NUM
1300  CALL GUEXIT(342)

C--MOLECULAR AXES CALCULATION
2000  CONTINUE
      CALL SMOLAX
      RETURN

C--TORSION ANGLE CALCULATION
3000  CONTINUE
      CALL HTORS
      RETURN

C--'#END' INSTRUCTION
4000  CONTINUE
      CALL XMONTR(-1)
      CALL XEND
      RETURN

C--'#TITLE' INSTRUCTION
5000  CONTINUE
      CALL XRCN
      RETURN
      END
