C $Log: not supported by cvs2svn $
C Revision 1.3  2001/02/26 10:26:49  richard
C Added changelog to top of file
C
C
CODE FOR INVERT
      SUBROUTINE INVERT
      CALL XSYSDC(-1,1)
      CALL XSFLSD
      RETURN
      END
C
CODE FOR XSFLSD
      SUBROUTINE XSFLSD
C--MAIN CONTROL ROUTINE FOR INVERTING THE NORMAL MATRIX
C  AND SOLVING THE LEAST SQUARES EQUATIONS.

\ISTORE
\ICOM24
\STORE
\XUNITS
\XLST12
\XLST24
\XLST50
\QSTORE
\QLST24

C--LOAD THE NEXT '#INSTRUCTION'
      NUM=KNXTOP(LSTOP,LSTNO,ICLASS)

C--CHECK IF WE SHOULD RETURN
      IF(NUM.LE.0) RETURN

C--BRANCH ON THE TYPE OF OPERATION
      GOTO (2000,6000,7000,8000,8500,8600,1300),NUM
1300  CALL GUEXIT(57)

C--'#INVERT'  -  INVERT THE NORMAL MATRIX
2000  CONTINUE
      CALL XSFLSE
      RETURN

C--'#SOLVE'  -  SOLVE THE NORMAL EQUATIONS
6000  CONTINUE
      CALL XSFLSG
      RETURN

C--'#NEWSHIFTS'  -  PREPARE LIST 24 WHEN IT IS OUT OF STEP
7000  CONTINUE
      I=KRDDPV(ISTORE(NFL),1)
\IDIM24
C--LOAD LIST 12 TO FIND THE NUMBER OF LEAST SQUARES PARAMETERS
      CALL XFAL12(0,0,I,J)
      IF ( IERFLG .LT. 0 ) RETURN
C--SET THE ORDER OF THE SHIFT LIST
      N24=N12
C--CREATE LIST 24
      CALL XCELST(24,ICOM24,IDIM24)
C--WRITE THE LIST TO THE DISC
      CALL XWLSTD(24,ICOM24,IDIM24,0,0)
      CALL XRSL
      CALL XCSAE
      RETURN

C--'#CYCLENDS' INSTRUCTION
8000  CONTINUE
      I=KRDDPV(ISTORE(NFL),1)
      CALL XCYCLE
      RETURN

C--'#END' INSTRUCTION
8500  CONTINUE
      CALL XMONTR(-1)
      CALL XEND
      RETURN
C
C--'#TITLE' INSTRUCTION
8600  CONTINUE
      CALL XRCN
      RETURN
      END
C
