C $Log: not supported by cvs2svn $
C Revision 1.5  2001/02/26 10:29:07  richard
C Added changelog to top of file
C
C
CODE FOR PUBLSH
      SUBROUTINE PUBLSH
      CALL XSYSDC(-1,1)
      CALL XPUBL
      RETURN
      END
C
CODE FOR XPUBL
      SUBROUTINE XPUBL
C--MAIN ROUTINE TO CONTROL PUBLICATION LISTINGS
C
C--
\XERVAL
C
C--LOAD THE NEXT '#INSTRUCTION'
      NUM=KNXTOP(LSTOP,LSTNO,ICLASS)
C--CHECK IF WE SHOULD RETURN
      IF(NUM.LE.0) RETURN
C--BRANCH ON THE TYPE OF OPERATION
C
C  REFLECTIONS  PARAMETERS  SUMMARY  GENERALEDIT  CIFOUT
C
      GO TO ( 2100, 2200, 2300, 2400, 2600, 1500 ) , NUM
1500  CONTINUE
      CALL XERHND ( IERPRG )
C
C--'#REFLECTIONS' INSTRUCTION
2100  CONTINUE
      CALL SPRT6P
      RETURN
C
C--'#PARAMETERS' INSTRUCTION
2200  CONTINUE
      CALL SPRT5P
      RETURN
C
2300  CONTINUE
C
C -- 'SUMMARY'
C
      CALL XSMMRY
      RETURN
C
2400  CONTINUE
C
C -- 'GENERALEDIT'
C
      CALL XGENED
      RETURN
2600  CONTINUE
C----- CIFOUT CIF OUTPUT
      CALL XCIFX
      RETURN
C
      END
C
