C $Log: not supported by cvs2svn $
C Revision 1.3  2001/02/26 10:30:23  richard
C Added changelog to top of file
C
C
CODE FOR RESTR
      SUBROUTINE RESTR
      CALL XSYSDC(-1,1)
      CALL XWASER
      RETURN
      END
C
CODE FOR XWASER
      SUBROUTINE XWASER
C--SUBROUTINE TO CONTROL THE APPLICATION AND CHECKING OF RESTRAINTS.
C
C--
\ISTORE
C
\STORE
C
\XUNITS
\QSTORE
C
C--LOAD THE NEXT '#INSTRUCTION'
      NUM=KNXTOP(LSTOP,LSTNO,ICLASS)
C--CHECK IF WE SHOULD RETURN
      IF(NUM.LE.0) RETURN
C--BRANCH ON THE TYPE OF OPERATION
      GOTO (2000,3000,4000,5000,1300),NUM
1300  CALL GUEXIT(341)
C
C--ROUTNE APPLY THE RESTRAINTS STORED IN LIST 16/26
2000  CONTINUE
      CALL XAPP16
      RETURN
C
C--ROUTINE TO CHECK THE RESTRAINTS STORED IN LIST 16/26
3000  CONTINUE
      CALL XCHK16
      RETURN
C
C--'#END' INSTRUCTION
4000  CONTINUE
      CALL XMONTR(-1)
      CALL XEND
      RETURN
C
C--'#TITLE' INSTRUCTION
5000  CONTINUE
      CALL XRCN
      RETURN
      END
