C $Log: not supported by cvs2svn $
C Revision 1.4  2001/09/19 08:50:10  ckp2
C Template #VISUALISE command for Steven's project.
C
C Revision 1.3  2001/02/26 10:30:24  richard
C Added changelog to top of file
C
C
CODE FOR WEIGHT
      SUBROUTINE WEIGHT
      CALL XSYSDC(-1,1)
      CALL XWAITS
       RETURN
      END

CODE FOR XWAITS
      SUBROUTINE XWAITS
C--SUBROUTINE TO CONTROL THE APPLICATION OF LIST 4 AND CHECK THE RESULTS
\XUNITS
C--LOAD THE NEXT '#INSTRUCTION'
      NUM=KNXTOP(LSTOP,LSTNO,ICLASS)
C--CHECK IF WE SHOULD RETURN
      IF(NUM.LE.0) RETURN
C--BRANCH ON THE TYPE OF OPERATION
      GOTO (2000,3000,4000,8000,8100,1300),NUM
1300  CALL GUEXIT(601)

C--ROUTINE TO APPLY THE PARAMETERS IN LIST 4
2000  CONTINUE
      CALL XAPP04
      RETURN

C--ROUTINE TO CHECK THE WEIGHTING SCHEME
3000  CONTINUE
      CALL XANAL
      RETURN
C--ROUTINE TO VISUALISE THINGS
4000  CONTINUE
      CALL ZMORE('Vis!',0)
      CALL XVANAL
      RETURN

C--'#END' INSTRUCTION
8000  CONTINUE
      CALL XMONTR(-1)
      CALL XEND
      RETURN

C--'#TITLE' INSTRUCTION
8100  CONTINUE
      CALL XRCN
      RETURN
      END
C
