module xchars_mod
integer IB,IH,NUMB(10),IPLUS,MINUS,IA,ISLASH,IEXP
integer ILB,IRB,ICOMMA,IEQUAL,IPOINT,ISEMIC,IQ,IX(3) 

COMMON/XCHARS/ IB,IH,NUMB,IPLUS,MINUS,IA,ISLASH,IEXP, &
&    ILB,IRB,ICOMMA,IEQUAL,IPOINT,ISEMIC,IQ,IX

end module

