module xlexic_mod

integer LK,LK1,LK2,NWCARD,LARG,MARG,MDARG,NARG
integer LCRD,MCRD,MDCRD,NCRD,MA,MB,MC,MD,ME,MF,MG,MH
integer MI,MJ,MK,ML,MM,MN,MO,MP,MQ,MR,MS,MT,MU,MV,MW,MX,MY
     
real Z

COMMON/XLEXIC/LK,LK1,LK2,NWCARD,LARG,MARG,MDARG,NARG, &
&   LCRD,MCRD,MDCRD,NCRD,MA,MB,MC,MD,ME,MF,MG,MH, &
&   MI,MJ,MK,ML,MM,MN,MO,MP,MQ,MR,MS,MT,MU,MV,MW,MX,MY,Z

end module
