module xopval_mod

INTEGER IOPCRY , IOPPUR , IOPLPC , IOPSSM , IOPMER
INTEGER IOPABS , IOPCOR , IOPREF , IOPFOU , IOPWEI , IOPANA, IOPTFC
INTEGER IOPMOD , IOPLSM , IOPHYD , IOPLSI , IOPLSC , IOPLEX, IOPL12
INTEGER IOPL16 , IOPCHK , IOPCPR , IOPSOR , IOPREO , IOPSFS, IOPPCH
INTEGER IOPDIS , IOPTOR , IOPPRA , IOPTLS , IOPAXS , IOPPPR, IOPREG
INTEGER IOPSIM , IOPTRI , IOPSLA , IOPFPL , IOPDAB , IOPDSP , IOPINV
INTEGER IOPGNP , IOPP22 , IOPSCP , IOPSGP , IOPQCK , IOPCMP, IOPBND
INTEGER IOPABN , IOPCMI , IOPEND , IOPPRC , IOPSPC
INTEGER IOPLSP , IOPINT , IOPLSE , IOPVER

COMMON /XOPVAL/ IOPCRY , IOPPUR , IOPLPC , IOPSSM , IOPMER , &
    IOPABS , IOPCOR , IOPREF , IOPFOU , IOPWEI , IOPANA , IOPTFC , &
    IOPMOD , IOPLSM , IOPHYD , IOPLSI , IOPLSC , IOPLEX , IOPL12 , &
    IOPL16 , IOPCHK , IOPCPR , IOPSOR , IOPREO , IOPSFS , IOPPCH , &
    IOPDIS , IOPTOR , IOPPRA , IOPTLS , IOPAXS , IOPPPR , IOPREG , &
    IOPSIM , IOPTRI , IOPSLA , IOPFPL , IOPDAB , IOPDSP , IOPINV , &
    IOPGNP , IOPP22 , IOPSCP , IOPSGP , IOPQCK , IOPCMP , IOPBND

COMMON /XOPMVL/ IOPABN , IOPCMI , IOPEND , IOPPRC , IOPSPC , &
    IOPLSP , IOPINT , IOPLSE , IOPVER

end module
