module xsflsw_mod
REAL SFOFC,SFCFC,WSFOFC,WSFCFC

LOGICAL CALC_ONLY, SCALE_ONLY, ENANTIO, CENTRO, NEWLHS, COS_ONLY, &
    ANOMAL, ISO_ONLY, L13_NEUTRON, REFPRINT, LAYERED, BATCHED, &
    PARTIALS, EXTINCT, TWINNED, SCALED_FOT

INTEGER JUMP, SFLS_TYPE, JREF_STACK_START, JREF_STACK_PTR, REFINE_TYPE

INTEGER, PARAMETER :: SFLS_CALC=1
INTEGER, PARAMETER :: SFLS_SCALE=2
INTEGER, PARAMETER :: SFLS_REFINE=3
INTEGER, PARAMETER :: REFINE_LSQ=0
INTEGER, PARAMETER :: REFINE_SD=1
INTEGER, PARAMETER :: REFINE_CG=2

COMMON/XSFLSW/ENANTIO, CENTRO, JUMP, &
    NEWLHS, COS_ONLY, ANOMAL, ISO_ONLY, L13_NEUTRON, REFPRINT, &
    SFLS_TYPE, LAYERED, BATCHED, PARTIALS, EXTINCT, TWINNED, &
    SCALED_FOT, JREF_STACK_START, JREF_STACK_PTR, REFINE_TYPE, &
    SFOFC,SFCFC,WSFOFC,WSFCFC

end module
