module xsflsw_mod
implicit none

    LOGICAL CALC_ONLY, SCALE_ONLY, ENANTIO, CENTRO, NEWLHS, COS_ONLY, &
    &   ANOMAL, ISO_ONLY, L13_NEUTRON, REFPRINT, LAYERED, BATCHED, &
    &   PARTIALS, EXTINCT, TWINNED, SCALED_FOT, UPDATE_PART

    INTEGER JUMP, SFLS_TYPE, SFLS_CALC, SFLS_SCALE, SFLS_REFINE, &
    &   JREF_STACK_START, JREF_STACK_PTR, REFINE_TYPE
    
    real SFOFC,SFCFC,WSFOFC,WSFCFC

    COMMON/XSFLSW/ENANTIO, CENTRO, JUMP, &
    &   NEWLHS, COS_ONLY, ANOMAL, ISO_ONLY, L13_NEUTRON, REFPRINT, &
    &   SFLS_TYPE, LAYERED, BATCHED, PARTIALS, EXTINCT, TWINNED,  &
    &   SCALED_FOT, JREF_STACK_START, JREF_STACK_PTR, REFINE_TYPE, &
    &   SFOFC,SFCFC,WSFOFC,WSFCFC

    PARAMETER (SFLS_CALC=1)
    PARAMETER (SFLS_SCALE=2)
    PARAMETER (SFLS_REFINE=3)

end module
