module xsfwk_mod

REAL SCALE,R,RW,WDFT,AMINF
REAL AC,BC,ACI,BCI,ACT,BCT,FO,FC,P,W,DF,WDF,TC,SST
REAL ST,A,C,S,COSP,SINP,WAVE,THETA1,THETA2,D,B,SCALEK,SCALEW
REAL SMIN,SMAX,RALL(12),ACD,BCD,ANOM,ENANT,CENANT,ACN,BCN,ACE
REAL XVALUE,LENAN,MENAN,MDENAN,NENAN,JENAN,LTEMPE,ACF,IENPRT

COMMON /XSFWK/SCALE,R,RW,WDFT,AMINF, &
    AC,BC,ACI,BCI,ACT,BCT,FO,FC,P,W,DF,WDF,TC,SST, &
    ST,A,C,S,COSP,SINP,WAVE,THETA1,THETA2,D,B,SCALEK,SCALEW, &
    SMIN,SMAX,RALL,ACD,BCD,ANOM,ENANT,CENANT,ACN,BCN,ACE, &
    XVALUE,LENAN,MENAN,MDENAN,NENAN,JENAN,LTEMPE,ACF,IENPRT

end module
