module xsfwk_mod

    real SCALE,R,RW,WDFT,AMINF, &
    &   ACR,BCR,ACI,BCI,ACT,BCT,FO,FC,P,W,DF,WDF,TC,SST, &
    &   ST,A,C,S,COSP,SINP,WAVE,THETA1,THETA2,D,B,SCALEK,SCALEW, &
    &   SMIN,SMAX,RALL(18),ACD,BCD,ANOM,ENANT,CENANT,ACN,BCN,ACE, &
    &   XVALUE, ACF
    integer LENAN,MENAN,MDENAN,NENAN,JENAN,LTEMPE,IENPRT 

    COMMON /XSFWK/SCALE,R,RW,WDFT,AMINF, &
    &   ACR,BCR,ACI,BCI,ACT,BCT,FO,FC,P,W,DF,WDF,TC,SST, &
    &   ST,A,C,S,COSP,SINP,WAVE,THETA1,THETA2,D,B,SCALEK,SCALEW, &
    &   SMIN,SMAX,RALL,ACD,BCD,ANOM,ENANT,CENANT,ACN,BCN,ACE, &
    &   XVALUE,LENAN,MENAN,MDENAN,NENAN,JENAN,LTEMPE,ACF,IENPRT
    
end module

