module xssval_mod

INTEGER ISSISS , ISSVER , ISSMAC(2) , ISSOPS(2)
INTEGER ISSDAT(4) , ISSSEG , ISSOLD , ISSNEW , ISSCIF , ISSFNF 
INTEGER ISSREA , ISSWRI , ISSBFS , ISSNBF , ISSPAG , ISSRLI 
INTEGER ISSBLI , ISSWLI , ISSRLF , ISSBLF , ISSWLF , ISSPRG(2) 
INTEGER ISSLSM , ISSSPD , ISSTIM , ISSL11 , ISSLNM , ISSINI 
INTEGER ISSSTA , ISSBAN , ISSSFI , ISSDAR , ISSTML , ISSFLC
INTEGER ISSMSG , ISSPRT , ISSEOF , ISSERF , ISSOKF , ISSSCR
INTEGER ISSUNK , ISSGEN , ISSFLM , ISSPAS , ISSEXP,  ISSUEQ
INTEGER ISSAPP , ISSUPD , ISSSEQ , ISSDAF , ISSBND,  ISSCSH
INTEGER ISSRAT , ISSMON

COMMON /XSSVAL/ ISSISS , ISSVER , ISSMAC , ISSOPS , &
    ISSDAT , ISSSEG , ISSOLD , ISSNEW , ISSCIF , ISSFNF, & 
    ISSREA , ISSWRI , ISSBFS , ISSNBF , ISSPAG , ISSRLI, &
    ISSBLI , ISSWLI , ISSRLF , ISSBLF , ISSWLF , ISSPRG, &
    ISSLSM , ISSSPD , ISSTIM , ISSL11 , ISSLNM , ISSINI, &
    ISSSTA , ISSBAN , ISSSFI , ISSDAR , ISSTML , ISSFLC, &
    ISSMSG , ISSPRT , ISSEOF , ISSERF , ISSOKF , ISSSCR, &
    ISSUNK , ISSGEN , ISSFLM , ISSPAS , ISSEXP,  ISSUEQ, &
    ISSAPP , ISSUPD , ISSSEQ , ISSDAF , ISSBND,  ISSCSH, &
    ISSRAT , ISSMON

end module
