
if(APPLE)
SET (ENV{CRYSDIR} "./")
EXECUTE_PROCESS (COMMAND ../crystals )
# EXECUTE_PROCESS (COMMAND ../crystals.app/Contents/MacOS/crystals ./ )
elif(WIN32)
SET (ENV{CRYSDIR} .\\ )
EXECUTE_PROCESS (COMMAND ../crystals.exe .\\ )
else()
SET (ENV{CRYSDIR} ./ )
EXECUTE_PROCESS (COMMAND ../crystals  )
endif()
