#
# This test takes a non-centro structure (cyclo) and tests lots of
# Fourier map features. (\FOUR only, not \SLANT)
#
\set time slow
\rele print CROUTPUT:
\use cyclo.in
# Do a pretty picture:
\MOLAX
ATOM FIRST UNTIL LAST
PLOT
END
#                                         NOFSQ, NOANOM
\LIST 23
MODIFY EXTINCTION=YES ANOM=NO
MINIMISE F-SQ=NO
END
\SFLS
SCALE
END
\FOUR
MAP TYPE=DIFF PRINT=YES
END
\PRINT 10
\FOUR
MAP TYPE=F-OBS PRINT=YES
END
\PRINT 10
\FOUR
MAP TYPE=F-CALC PRINT=YES
END        
\PRINT 10
\FOUR
MAP TYPE=2FO-FC PRINT=YES
END
\PRINT 10
\FOUR
MAP TYPE=OPTIMAL PRINT=YES
END
\PRINT 10
\FOUR
MAP TYPE=FO-PATTERSON PRINT=YES
END
\PRINT 10
\FOUR
MAP TYPE=FC-PATTERSON PRINT=YES
END
\PRINT 10
\FOUR
MAP TYPE=FO-FC-SQP PRINT=YES
END
\PRINT 10
\FOUR
MAP TYPE=FOSQ-FCSQ-P PRINT=YES
END
\PRINT 10
\FOUR
MAP TYPE=DIFF PRINT=YES
REFLECTION WEIGHT=SIM
END
\PRINT 10
\FOUR
MAP TYPE=F-OBS PRINT=YES
REFLECTION WEIGHT=SIM
END
\PRINT 10
\FOUR
MAP TYPE=F-CALC PRINT=YES
REFLECTION WEIGHT=SIM
END        
\PRINT 10
\FOUR
MAP TYPE=2FO-FC PRINT=YES
REFLECTION WEIGHT=SIM
END
\PRINT 10
\FOUR
MAP TYPE=OPTIMAL PRINT=YES
REFLECTION WEIGHT=SIM
END
\PRINT 10
\FOUR
MAP TYPE=FO-PATTERSON PRINT=YES
REFLECTION WEIGHT=SIM
END
\PRINT 10
\FOUR
MAP TYPE=FC-PATTERSON PRINT=YES
REFLECTION WEIGHT=SIM
END
\PRINT 10
\FOUR
MAP TYPE=FO-FC-SQP PRINT=YES
REFLECTION WEIGHT=SIM
END
\PRINT 10
\FOUR
MAP TYPE=FOSQ-FCSQ-P PRINT=YES
REFLECTION WEIGHT=SIM
END
\PRINT 10
\LIST 4
END
\WEIGHT
END
\LIST 12 
FULL FIRST(X'S) UNTIL LAST 
END
\SFLS 
REFINE
REFINE
REFINE
END
\LIST 12 
FULL FIRST(X'S, U[ISO]) UNTIL LAST
\SFLS 
REFINE
REFINE
REFINE 
REFINE 
\LIST 12 
FULL FIRST(U'S) UNTIL LAST EXTPARAM
\SFLS 
REFINE
REFINE
END
\LIST 4
SCHEME 17
END
\WEIGHT
END
\FOUR
MAP TYPE=DIFF PRINT=YES
REFLECTION WEIGHT=LIST-6
END
\PRINT 10
\FOUR
MAP TYPE=F-OBS PRINT=YES
REFLECTION WEIGHT=LIST-6
END
\PRINT 10
\FOUR
MAP TYPE=F-CALC PRINT=YES
REFLECTION WEIGHT=LIST-6
END        
\PRINT 10
\FOUR
MAP TYPE=2FO-FC PRINT=YES
REFLECTION WEIGHT=LIST-6
END
\PRINT 10
\FOUR
MAP TYPE=OPTIMAL PRINT=YES
REFLECTION WEIGHT=LIST-6
END
\PRINT 10

\ skip the weighted pattersons - they throw up a miriad small errors
\end




\FOUR
MAP TYPE=FO-PATTERSON PRINT=YES
REFLECTION WEIGHT=LIST-6
END
\PRINT 10
\FOUR
MAP TYPE=FC-PATTERSON PRINT=YES
REFLECTION WEIGHT=LIST-6
END
\PRINT 10
\FOUR
MAP TYPE=FO-FC-SQP PRINT=YES
REFLECTION WEIGHT=LIST-6
END
\PRINT 10
\FOUR
MAP TYPE=FOSQ-FCSQ-P PRINT=YES
REFLECTION WEIGHT=LIST-6
END
\PRINT 10
\FINISH
